### ISSUE TITLE
Example names do not contain library name

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_AzureIoT#17]
The Adafruit CircuitPython library standard is to include the library name in all example names. Every example is included on its own in the example bundle, and without the library name included, the bundle gets confusing and unusable.

@jimbobbennett You recently made changes to this library and its examples. Do you have any suggestions as to how best to include the library name `azureiot_` in the example names? I notice you included `iot` in all of them, I would suggest that be updated to `azureiot_`, but I would like to hear your thoughts.

**Comment by jimbobbennett** [comment]
Apologies - I didn't realize that was the standard.

I've raised #19 to use `azureiot_` as a prefix. The use of IoT was because the examples were for Azure IoT Central and Azure IoT Hub, so I wanted to include the service name that the example connects to. Having `azureiot_central` or `azureiot_hub` as a prefix works.
